--
-- Create the table if it doesn't exist.
--
CREATE TABLE IF NOT EXISTS `PART_COL_STATS` (
 `CS_ID` bigint(20) NOT NULL,
 `DB_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
 `TABLE_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
 `PARTITION_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
 `COLUMN_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
 `COLUMN_TYPE` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
 `PART_ID` bigint(20) NOT NULL,
 `LONG_LOW_VALUE` bigint(20),
 `LONG_HIGH_VALUE` bigint(20),
 `DOUBLE_HIGH_VALUE` double(53,4),
 `DOUBLE_LOW_VALUE` double(53,4),
 `BIG_DECIMAL_LOW_VALUE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin,
 `BIG_DECIMAL_HIGH_VALUE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin,
 `NUM_NULLS` bigint(20) NOT NULL,
 `NUM_DISTINCTS` bigint(20),
 `AVG_COL_LEN` double(53,4),
 `MAX_COL_LEN` bigint(20),
 `NUM_TRUES` bigint(20),
 `NUM_FALSES` bigint(20),
 `LAST_ANALYZED` bigint(20) NOT NULL,
  PRIMARY KEY (`CS_ID`),
  CONSTRAINT `PART_COL_STATS_FK` FOREIGN KEY (`PART_ID`) REFERENCES `PARTITIONS` (`PART_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE INDEX PCS_STATS_IDX ON PART_COL_STATS (DB_NAME,TABLE_NAME,COLUMN_NAME,PARTITION_NAME) USING BTREE;
