ALTER TABLE `COLUMNS_V2` MODIFY `COLUMN_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;
ALTER TABLE `PART_COL_PRIVS` MODIFY `COLUMN_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE `TBL_COL_PRIVS` MODIFY `COLUMN_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE `SORT_COLS` MODIFY `COLUMN_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE `TAB_COL_STATS` MODIFY `COLUMN_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;
ALTER TABLE `PART_COL_STATS` MODIFY `COLUMN_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;
